version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.2
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: echo 'Hello world!'
