version: 2.1
jobs:
  build:
    machine:
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Push image
          command: |
            docker build -t $DOCKERHUB_USERNAME/faru.jp:$CIRCLE_SHA1 .
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker tag $DOCKERHUB_USERNAME/faru.jp:$CIRCLE_SHA1 $DOCKERHUB_USERNAME/faru.jp:latest
            docker push $DOCKERHUB_USERNAME/faru.jp:$CIRCLE_SHA1
            docker push $DOCKERHUB_USERNAME/faru.jp:latest

  manifest:
    working_directory: ~/repo
    machine:
      image: "circleci/classic:201808-01"
    steps:
      - kube-orb/install
      - run:
          command: >
            curl -Lo minikube
            https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            \
              && chmod +x minikube
            sudo cp minikube /usr/local/bin && rm minikube

            sudo -E minikube start --vm-driver=none --cpus 2 --memory 2048
          name: Start minikube
      - add_ssh_keys:
          fingerprints:
            - "38:4e:17:28:8f:7a:75:c6:17:ae:c9:9c:38:09:ab:3f"
      - run: echo -e "Host bitbucket.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: git clone -b master git@bitbucket.org:faru_ryo/kubernetes-common.git
      - run: kubectl patch -f kubernetes-common/web/www-deploy.yaml --dry-run -o yaml -p '{"spec":{"template":{"spec":{"containers":[{"name":"farujp","image":"faruryo/faru.jp:hogehoge"}]}}}}' > www-deploy.yaml
      - run: cp -f www-deploy.yaml kubernetes-common/web/www-deploy.yaml
      - run: |
          cd kubernetes-common
          git add web/www-deploy.yaml
          git config --global user.email circleci
          git config --global user.name circleci
          git commit -m "update www.faru.jp $CIRCLE_SHA1"
          git push origin release/$CIRCLE_SHA1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: DOCKERHUB
          filters:
            branches:
              only: master
      - manifest:
          requires:
            - build
          filters:
            branches:
              only: master

orbs:
  kube-orb: circleci/kubernetes@1.0.0
